
name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [web-app, machine-learning-client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 

      - name: Install dependencies
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)

      - name: Enter Pipenv shell and Lint with pylint
        run: |
          cd ${{ matrix.subdir }}
          pipenv run pylint **/*.py

      - name: Enter Pipenv shell and Format with black
        run: |
          cd ${{ matrix.subdir }}
          pipenv run black --diff --check .